name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Filename is hello_world.py
      id: filename-is-hello_world-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Filename is hello_world.py
        setup-command: ''
        command: python3 ./hello_world.py
        timeout: 10
        max-score: 50
    - name: Program prints "Hello, world!"
      id: program-prints-hello-world
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Program prints "Hello, world!"
        setup-command: ''
        command: python3 ./hello_world.py
        input: ''
        expected-output: Hello, world!
        comparison-method: contains
        timeout: 10
        max-score: 50
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        FILENAME-IS-HELLO_WORLD-PY_RESULTS: "${{steps.filename-is-hello_world-py.outputs.result}}"
        PROGRAM-PRINTS-HELLO-WORLD_RESULTS: "${{steps.program-prints-hello-world.outputs.result}}"
      with:
        runners: filename-is-hello_world-py,program-prints-hello-world
